@isTest
private class TwitterAuthorizationTestSuite {

	@isTest static void requestAuthorizationToken_success() {
		// Implement test code
	}

	@isTest static void requestAuthorizationToken_emptyTwitterSettings() {
		// Implement test code
	}

	@isTest static void requestAuthorizationToken_invalidConsumerKeys() {
		// Implement test code
	}

	@isTest static void testAuthenticationUser_success() {
		// Implement test code
	}

	@isTest static void requestAccessToken_success() {
		// Implement test code
	}

	@isTest static void requestAccessToken_invalidVerifier() {
		// Implement test code
	}

}